version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis-data:/data

  web:
    build: .
    container_name: pipeline-web
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - UPLOAD_ROOT=/shared_uploads # Set UPLOAD_ROOT to the shared volume path
    ports:
      - "8000:8000"
    volumes:
      - shared_uploads_volume:/shared_uploads # Mount the shared volume
    command: > # This will be passed as arguments to the ENTRYPOINT script
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000

  celery-worker:
    build: .
    container_name: pipeline-worker
    depends_on:
    - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - UPLOAD_ROOT=/shared_uploads # Set UPLOAD_ROOT to the shared volume path
    volumes:
      - shared_uploads_volume:/shared_uploads # Mount the shared volume
    command: > # This will be passed as arguments to the ENTRYPOINT script
      celery
      -A app.tasks:celery_app
      worker
      -P threads
      -c 8
      -l info

volumes:
  redis-data:
  shared_uploads_volume: # Define the named volume