# docker-compose.yml
version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis-data:/data

  web:
    build: .
    container_name: pipeline-web
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "8000:8000"
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000

  celery-worker:
    build: .
    container_name: pipeline-worker
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    user: "1000:1000"
    command: >
      celery
      -A app.tasks:celery_app
      worker
      -P threads
      -c 8
      -l info

volumes:
  redis-data:
